language: node_js
node_js:
 - "node"

  cache: npm

script:
  - npm run build

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2
  cleanup: false
  keep_history: true
  local_dir: dist
  on:
    branch: master
