language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run test:unit
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2
  keep_history: true
  local_dir: dist
